name: project_dapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  shared_preferences: ^2.3.2
  provider: ^6.1.0
  # Sui 錢包整合
  url_launcher: ^6.2.0
  flutter_secure_storage: ^9.0.0
  # WalletConnect for mobile wallet integration
  walletconnect_flutter_v2: ^2.1.0
  qr_flutter: ^4.1.0
  # 地圖搜尋功能
  flutter_typeahead: ^4.8.0
  # WebView for Sui dApp integration
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/vehicles.json
    - assets/car_icon.png
